In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_price.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

In [2]:
df = df[df['Cocoa Percent'] <= 70]
df.reset_index(drop = True, inplace = True)
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
995,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
996,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
997,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
998,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0
999,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil,97500.0

In [3]:
grouped = df.groupby(['Company', 'Review Date'])['Rating'].mean()
companies = grouped.unstack()
companies

Review Date,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Company,,,,,,,,,,,,
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.500000,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Zokoko,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,65.0,NaN
Zotter,NaN,NaN,NaN,NaN,60.0,67.5,69.285714,NaN,NaN,NaN,NaN,NaN
hello cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.00,NaN,NaN
hexx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN
twenty-four blackbirds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN

In [4]:
companies.columns.name = None
companies.index.name = None

In [5]:
filtered_df = df[df['Review Date'] >= 2012]
mean_ratings = filtered_df.groupby('Company')['Rating'].mean()
mean_ratings.index.name = None
mean_ratings

A. Morin                  67.608696
Acalli                    75.000000
Alain Ducasse             55.000000
Alexandre                 70.000000
Altus aka Cao Artisan     56.111111
                            ...
Zokoko                    65.000000
Zotter                    69.285714
hello cocoa               55.000000
hexx                      60.000000
twenty-four blackbirds    65.000000
Name: Rating, Length: 245, dtype: float64

In [6]:
best_ratings = mean_ratings.sort_values(ascending=False, kind='mergesort')
best_ratings = best_ratings.head(10)
mean_ratings.index.name = None
best_ratings

Patric                     80.0
Tobago Estate (Pralus)     80.0
Willie's Cacao             80.0
L.A. Burdick (Felchlin)    77.5
Matale                     77.5
Acalli                     75.0
Amedei                     75.0
Askinosie                  75.0
Bonnat                     75.0
Cacao de Origen            75.0
Name: Rating, dtype: float64

In [7]:
chocolates_to_sell = df[df['Company'].isin(best_ratings.index)]
chocolates_to_sell = chocolates_to_sell.reset_index(drop = True)
chocolates_to_sell

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Acalli,"Chulucanas, El Platanal",2015,70.0,U.S.A.,75.0,Blend,Peru,131250.0
1,Acalli,"Tumbes, Norandino",2015,70.0,U.S.A.,75.0,Criollo,Peru,131250.0
2,Amedei,"Piura, Blanco de Criollo",2012,70.0,Italy,75.0,Blend,Peru,131250.0
3,Amedei,Porcelana,2007,70.0,Italy,80.0,Criollo (Porcelana),Venezuela,140000.0
4,Amedei,Chuao,2007,70.0,Italy,100.0,Trinitario,Venezuela,175000.0
5,Amedei,Ecuador,2007,70.0,Italy,60.0,Trinitario,Ecuador,105000.0
6,Amedei,Jamaica,2007,70.0,Italy,60.0,Trinitario,Jamaica,105000.0
7,Amedei,Grenada,2007,70.0,Italy,70.0,Trinitario,Grenada,122500.0
8,Amedei,Venezuela,2007,70.0,Italy,75.0,Trinitario (85% Criollo),Venezuela,131250.0
9,Amedei,Madagascar,2007,70.0,Italy,80.0,Trinitario (85% Criollo),Madagascar,140000.0
10,Amedei,Trinidad,2007,70.0,Italy,70.0,Trinitario,Trinidad,122500.0
11,Amedei,Toscano Black,2007,63.0,Italy,70.0,Blend,Other,110250.0
12,Amedei,Toscano Black,2006,70.0,Italy,100.0,Blend,Other,175000.0
13,Amedei,Toscano Black,2006,66.0,Italy,80.0,Blend,Other,132000.0
14,Askinosie,Mababa,2016,68.0,U.S.A.,75.0,Trinitario,Tanzania,127500.0
15,Askinosie,Cortes,2011,70.0,U.S.A.,75.0,Trinitario,Honduras,131250.0
16,Askinosie,San Jose del Tambo,2007,70.0,U.S.A.,60.0,Forastero (Arriba),Ecuador,105000.0
17,Bonnat,Surfin,2014,65.0,France,75.0,Blend,"Venez,Africa,Brasil,Peru,Mex",121875.0
18,Cacao de Origen,"Chuao, Aragua region",2014,70.0,Venezuela,75.0,Trinitario,Venezuela,131250.0
19,L.A. Burdick (Felchlin),Brazil,2012,70.0,U.S.A.,80.0,Blend,Brazil,140000.0
20,L.A. Burdick (Felchlin),Chuao,2012,68.0,U.S.A.,75.0,Trinitario,Venezuela,127500.0
21,L.A. Burdick (Felchlin),Madagascar,2009,64.0,U.S.A.,70.0,Trinitario,Madagascar,112000.0
22,L.A. Burdick (Felchlin),Bolivian,2009,68.0,U.S.A.,60.0,Blend,Bolivia,102000.0
23,Matale,"Somia, 2013",2013,68.0,Australia,80.0,Trinitario,Madagascar,136000.0
24,Matale,Blend,2013,70.0,Australia,75.0,Trinitario,"PNG, Vanuatu, Mad",131250.0
25,Patric,Signature Blend,2011,70.0,U.S.A.,75.0,Blend,Other,131250.0
26,Patric,Madagascar,2009,67.0,U.S.A.,70.0,Trinitario,Madagascar,117250.0
27,Patric,"Rio Caribe, Paria Penninsula",2009,70.0,U.S.A.,70.0,Trinitario,Venezuela,122500.0
28,Patric,Madagascar,2007,70.0,U.S.A.,80.0,Trinitario,Madagascar,140000.0
29,Patric,"Piura, Choc. Garage Exclusive",2013,67.0,U.S.A.,80.0,Blend,Peru,134000.0
30,Tobago Estate (Pralus),"Roxborough, Tobago",2012,70.0,France,80.0,Trinitario,Tobago,140000.0
31,Willie's Cacao,Los Llanos,2016,70.0,U.K.,80.0,Blend,Colombia,140000.0
32,Willie's Cacao,Java,2010,69.0,U.K.,75.0,Blend,Indonesia,129375.0
33,Willie's Cacao,San Martin,2009,70.0,U.K.,60.0,Blend,Peru,105000.0

In [8]:
priceSum = chocolates_to_sell['price(100g)'].sum()
priceSum

4377250.0